### ISSUE TITLE
appViewInternal is not available

### ISSUE THREAD

**Issue by broomdodger** [thomaswilburn/Caret#326]
acer c720 chromebook
chrome 39.0.2171.96
caret 1.4.36

I found this in console.
Is it a problem? and known?
Is it something I did?

```
chrome.appViewInternal is not available: 'appViewInternal' requires Google Chrome dev channel or newer, but this is the stable channel.extensions::binding:471 Binding.generate
extensions::uncaught_exception_handler:8 Error in response to fileSystem.chooseEntry: TypeError: Cannot read property 'slice' of undefined
    at Object.callback (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/fileManager.js:36:17)
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/fileManager.js:34:23
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:38:35
    at Object.fire (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:37:14)
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/ui/keys.js:114:15extensions::uncaught_exception_handler:8 handler
extensions::sendRequest:82 Unchecked runtime.lastError while running fileSystem.chooseEntry: User cancelled
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/fileManager.js:34:23
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:38:35
    at Object.fire (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:37:14)
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/ui/keys.js:114:15extensions::sendRequest:82 handleResponse
extensions::uncaught_exception_handler:8 Error in response to fileSystem.chooseEntry: TypeError: Cannot read property 'slice' of undefined
    at Object.callback (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/fileManager.js:36:17)
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/fileManager.js:34:23
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:38:35
    at Object.fire (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:37:14)
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/ui/keys.js:114:15extensions::uncaught_exception_handler:8 handler
extensions::sendRequest:82 Unchecked runtime.lastError while running fileSystem.chooseEntry: User cancelled
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/fileManager.js:34:23
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:38:35
    at Object.fire (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:37:14)
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/ui/keys.js:114:15extensions::sendRequest:82 handleResponse
```

**Comment by thomaswilburn** [comment]
No, it's an internal warning, and non-fatal.
