### ISSUE TITLE
Tabs not closing

### ISSUE THREAD

**Issue by TheThirdOne** [thomaswilburn/Caret#387]
Occasionally, a tab will refuse to close.

Steps to Reproduce:
  1. open an untitled.txt tab
  2. Start to save (ctrl-s), but hit cancel
  3. hitting o on the tab or ctrl-w does not close it.

**Comment by thomaswilburn** [comment]
Huh. Do you see any errors in the console when this happens? When the files app changed to the material design, I believe we started seeing more errors on user cancelling, that kind of thing, and as a result we may be hitting a problem somewhere else in the pipeline.

**Comment by TheThirdOne** [comment]
Here is the error on almost saving:
```
Error in response to fileSystem.chooseEntry: TypeError: Cannot read property 'name' of null
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/tab.js:93:35
    at Object.callback (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/storage/file.js:35:28)
    at Object.File.open (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/storage/file.js:31:25)
    at Tab.save (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/tab.js:87:12)
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/fileManager.js:51:8
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:38:35
    at Object.fire (chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/command.js:37:14)
    at chrome-extension://fljalecfjciodhpcledpamjachpmelml/js/ui/keys.js:114:15handler @ extensions::uncaught_exception_handler:8exports.handle @ extensions::uncaught_exception_handler:100safeCallbackApply @ extensions::sendRequest:23handleResponse @ extensions::sendRequest:73
```

**Comment by thomaswilburn** [comment]
Awesome, that's very helpful. I'll take a look this weekend and push out a fix.
